# version: '3.9'

services:
  web:
    build: .
    ports:
      - "8005:8005"
    volumes:
      - ./logs:/app/logs
    env_file:
      - .env
    command: >
      python manage.py runserver 0.0.0.0:8005 --settings=backend.settings
