# Generated by Django 5.2.3 on 2025-06-12 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('copilot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='moderationresult',
            name='is_checked_by_moderator',
            field=models.BooleanField(default=False),
        ),
    ]
