# Generated by Django 5.2.3 on 2025-06-12 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('copilot', '0002_moderationresult_is_checked_by_moderator'),
    ]

    operations = [
        migrations.AddField(
            model_name='moderationresult',
            name='moderator_tags',
            field=models.TextField(blank=True, default=''),
        ),
    ]
