# Generated by Django 5.2.3 on 2025-06-13 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('copilot', '0003_moderationresult_moderator_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='moderationresult',
            name='moderator_verdict',
            field=models.TextField(blank=True, help_text='Комментарий/решение модератора', null=True),
        ),
    ]
